#!/usr/bin/env python3
"""Generate data/triage/usable_layered_report.md from closeability_full.csv.

Applies the calibrated USABLE gate (see scan_closeability_full.py for the
calibration story against the four ground-truth cases):

  page USABLE  = not rep_flag and not bad_title
                 and n_mid >= 8 and cov_mid >= 0.2 and largest_frac <= 0.7
  permit USABLE = any candidate page passes

  page BORDERLINE (worth an eyeball) = not rep_flag and not bad_title and
                 n_mid >= 5 and cov_mid >= 0.1 and largest_frac <= 0.8
                 (i.e. relaxed gate) but not USABLE
  Also borderline: permits whose ONLY passing pages are rep_flagged with
  strong metrics (a mis-flag would hide a usable permit).

Reads only our own CSVs; writes only the report file. Rerunnable.
"""
import csv
import os
import sys
from collections import defaultdict

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from probe2_sf import ROOT

CLOSE = os.path.join(ROOT, "data", "triage", "closeability_full.csv")
LAYERED = os.path.join(ROOT, "data", "triage", "layered_plans.csv")
SEEN = LAYERED + ".seen"
CRASHED = LAYERED + ".crashed"
OUT = os.path.join(ROOT, "data", "triage", "usable_layered_report.md")

GATE = dict(n_mid=8, cov_mid=0.2, largest_frac=0.7)
RELAXED = dict(n_mid=5, cov_mid=0.1, largest_frac=0.8)


def fnum(x, d=0.0):
    try:
        return float(x)
    except (TypeError, ValueError):
        return d


def passes(r, cut):
    return (r["rep_flag"] == "False" and r["bad_title"] == "False"
            and fnum(r["n_mid"]) >= cut["n_mid"]
            and fnum(r["cov_mid"]) >= cut["cov_mid"]
            and fnum(r["largest_frac"]) <= cut["largest_frac"])


def main():
    rows = list(csv.DictReader(open(CLOSE)))
    # de-dupe retried keys: prefer the scored (non-crash) row
    by_key = {}
    for r in rows:
        k = (r["permit"], r["doc_id"], r["page"])
        note = r.get("note") or ""
        if k in by_key and (note.startswith("crash:") or note.startswith("dl_err")):
            continue
        by_key[k] = r
    rows = list(by_key.values())

    by_permit = defaultdict(list)
    for r in rows:
        by_permit[r["permit"]].append(r)

    layered_permits = set()
    layered_docs = set()
    for r in csv.DictReader(open(LAYERED)):
        layered_permits.add(r["permit"])
        layered_docs.add(r["doc_id"])
    n_seen = len(set(open(SEEN).read().split())) if os.path.exists(SEEN) else 0
    n_crashed = (len({l.split()[0] for l in open(CRASHED) if l.strip()})
                 if os.path.exists(CRASHED) else 0)

    usable = {}      # permit -> best passing row
    borderline = {}  # permit -> best relaxed-pass row (not usable)
    flag_watch = {}  # permit -> best rep_flagged row w/ strong metrics
    for permit, rs in by_permit.items():
        ps = [r for r in rs if passes(r, GATE)]
        if ps:
            usable[permit] = max(ps, key=lambda r: (fnum(r["n_mid"]), fnum(r["cov_mid"])))
            continue
        bs = [r for r in rs if passes(r, RELAXED)]
        if bs:
            borderline[permit] = max(bs, key=lambda r: (fnum(r["n_mid"]), fnum(r["cov_mid"])))
            continue
        fs = [r for r in rs if r["rep_flag"] == "True" and r["bad_title"] == "False"
              and fnum(r["n_mid"]) >= GATE["n_mid"] and fnum(r["cov_mid"]) >= GATE["cov_mid"]
              and fnum(r["largest_frac"]) <= GATE["largest_frac"]]
        if fs:
            flag_watch[permit] = max(fs, key=lambda r: (fnum(r["n_mid"]), fnum(r["cov_mid"])))

    def table(d):
        lines = ["| permit | doc | page | n_mid | cov_mid | largest | core segs | fpp | layers |",
                 "|---|---|---|---|---|---|---|---|---|"]
        for p in sorted(d):
            r = d[p]
            lay = (r["layers"] or "").replace("|", ", ")
            if len(lay) > 70:
                lay = lay[:67] + "..."
            lines.append(f"| {p} | {r['doc_id']} | {r['page']} | {r['n_mid']} | "
                         f"{r['cov_mid']} | {r['largest_frac']} | {r['n_core_segs']} | "
                         f"{r['best_fpp']} | {lay} |")
        return "\n".join(lines)

    n_scanned_docs = len(layered_docs) + n_seen  # docs with layers + docs scanned clean
    md = f"""# Geometry-USABLE wall-layer permits — full-corpus scan

Generated by scripts/report_usable_layered.py from
data/triage/closeability_full.csv (candidates: data/triage/layered_plans.csv).

## Headline

- **Permits with named wall layers anywhere in the downloaded corpus:
  {len(layered_permits)}** (from {len(layered_docs)} layered docs; {n_seen} docs
  scanned clean, {n_crashed} docs skipped/crashed — see caveats).
- **Permits with >=1 page passing the calibrated USABLE gate: {len(usable)}**
- Borderline permits worth a human/agent eyeball: {len(borderline)}
  (+ {len(flag_watch)} rep-flagged permits whose metrics would otherwise pass).

## The calibrated gate

Page is USABLE iff ALL of:
- `rep_flag = False` — page has >=60 long wall segments on a clean wall-core
  layer (wall-named, not /3D|HATCH/i). Load-bearing: metric cuts alone cannot
  reject 25-33341's `.3D` solid export.
- `bad_title = False` — title block does not read SECTION/ELEVATION/etc.
- `n_mid >= {GATE['n_mid']}` — room-band polygons (0.2%-8% of wall bbox).
- `cov_mid >= {GATE['cov_mid']}` — room-band area share of wall bbox
  (plain coverage is fragment-inflatable; cov_mid is not).
- `largest_frac <= {GATE['largest_frac']}` — not one giant unsubdivided blob.
Metrics are the best over an fpp sweep {{0.05, 0.1, 0.2}} (door-gap closing is
scale-dependent; a fixed fpp under-closes small-scale drawings).

Calibration on the four knowns (all correct):
- 14-11290-NEWC d1494156 p3 (USABLE): mid=15 cov_mid=0.253 largest=0.192 PASS
- 26-10321-RNVN d9058456 p18 (USABLE): mid=46 cov_mid=0.391 largest=0.063 PASS
- 25-33341-NEWC d8640130 (NOT): rep_flag (`A - Walls - Exterior.3D`) REJECT
- 24-22310-RNVN d7671011 (NOT): rep_flag (`8_Wall_Hatch`, no clean core) REJECT

## USABLE permits ({len(usable)})

{table(usable)}

## Borderline — eyeball these ({len(borderline)})

Pass a relaxed gate (mid>={RELAXED['n_mid']}, cov_mid>={RELAXED['cov_mid']},
largest<={RELAXED['largest_frac']}) but not the main one:

{table(borderline)}

## Rep-flagged but metrics pass ({len(flag_watch)})

Wall layers are 3D/hatch-named (or no clean core layer) yet closure metrics
look good — a mis-flag here would hide a usable permit; worth a spot check:

{table(flag_watch)}

## Verdict on "only 2 of ~150 usable"

See final numbers above. The old claim came from data/triage/closeability.csv,
which only scanned permits having a LABELED floor_plan page and scored one
page per permit at a fixed fpp=0.1 — a biased slice with a scale-sensitive
metric (it scored the bank's ground-truth-usable page at n_mid=4/cov=0.086).

## Caveats

- Candidate pages per permit capped at top-5 by harvested wall_segs; a permit
  whose only clean floor plan ranks 6th+ would be missed (unlikely: floor
  plans dominate segment counts once section sheets are title-filtered).
- Docs >300MB skipped ({n_crashed} total skip/crash docs incl. these).
- harvest page scan caps at first 60 pages per doc (harvest_layered.py).
- "USABLE" = rooms polygonize structurally; scale parse + room anchoring can
  still fail downstream (see probe24 method).
- Gate calibrated on only 4 ground-truth cases; borderline band exists
  precisely because the cut is coarse.
"""
    open(OUT, "w").write(md)
    print(f"wrote {OUT}")
    print(f"named-wall-layer permits: {len(layered_permits)}")
    print(f"USABLE permits: {len(usable)}")
    for p in sorted(usable):
        r = usable[p]
        print(f"  {p}  doc {r['doc_id']} p{r['page']}  mid={r['n_mid']} "
              f"cov_mid={r['cov_mid']} largest={r['largest_frac']}")
    print(f"borderline: {len(borderline)}  flag-watch: {len(flag_watch)}")


if __name__ == "__main__":
    main()
